### ISSUE TITLE
Create a Nuget package

### ISSUE THREAD

**Issue by MendelMonteiro** [MikePopoloski/StringFormatter#2]

**Comment by MikePopoloski** [comment]
As mentioned in the pull request, I don't really want to support a proper NuGet package with all the various platforms people might want; I'm going to generate a single .cs file you can include to get the whole library, which avoids any distribution headaches.

**Comment by MendelMonteiro** [comment]
By the way I've released a nuget package from my fork (https://www.nuget.org/packages/StringFormatter/) so that we could reference it from our zero-allocation logger https://github.com/Abc-Arbitrage/ZeroLog.

**Comment by MikePopoloski** [comment]
Cool, thanks. I put a unified StringFormatter.cs file in the root directory for anyone who doesn't want to depend on a package.
